version: '3.4'

services:
  redis:
    restart: 'no'
    image: redis:latest
    command: --loglevel verbose

  rcli:
    restart: 'no'
    image: redis:latest
    depends_on:
      - redis
    command: >
      sh -c 'redis-cli -h redis '

  readis:
    restart: 'no'
    image: hollodotme/readis
    ports:
      - 8080:80
    volumes:
      - ./config:/code/config:ro
    depends_on:
      - redis

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    ports:
      - "8081:80"
